image: debian:jessie

before_script:
  - apt-get update && apt-get install -yq hugo
  - hugo version

test:
  script:
  - hugo

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
