baseURL:                    https://zihao.me/
canonifyURLs:               true
# baseUrl: /  
defaultContentLanguage: en
enableEmoji:                true
googleAnalytics:            UA-62762041-1
languageCode:               en-us
# permalinks: maybe
theme:                      cactus-plus
title:                      Zihao Zhang
# hasCJKLanguage:             true

params:
  name: Zihao Zhang
  description: Running myself like a Startup
  bio: Running myself like a Startup
  twitter: zzh8829
  enableRSS: true
  disqusShortname: zihaosblog
  enableDisqus: true
  enableGoogleAnalytics: true
  customCSS:
  - css/zihao.css
  # home: ""
  # about: ""
  # archive: ""
  # subscribe: ""
  # olderPosts: ""
  # newerPosts: ""
  # readMore: ""
  copyright: Copyright © 2017 Zihao Zhang, Licensed under <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a> <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"></a> 
  # aboutAuthor: 'I am so interesting.'
  # tweet: ""
  # share: ""
  # title404: ""
  # subtitle404: ""
  iconFont: font-awesome
  staticPages: About Tags
social:
  facebook-square: https://facebook.com/zihao.pro.zhang
  twitter-square: https://twitter.com/zzh8829
  github-square: https://github.com/zzh8829

